FootballLeague/FootballLeague/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootballLeague.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Teams");
        }
    }
}

FootballLeague/FootballLeague/Controllers/MatchesController.cs
using DAL;
using Models;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootballLeague.Controllers
{
    public class MatchesController : Controller
    {
        private IMatchesService _matchesService;
        private ITeamsService _teamsService;
        const string sameTeamError = "You cant use the same team for home and away side!";
        const string negativeGoalsError = "Goals should never be a negative number!";
        public MatchesController(IMatchesService matchesService, ITeamsService teamsService)
        {
            _matchesService = matchesService;
            _teamsService = teamsService;
        }
        // GET: Matches
        public ActionResult Index()
        {
            var model = _matchesService.GetAll();

            return View(model);
        }
        public ActionResult AddMatch()
        {
            var teams = _teamsService.GetTeamsViewModel();
            var model = _matchesService.CreateNewModel(teams);
            return View(model);
        }
        public ActionResult EditMatch(int id)
        {
            var teams = _teamsService.GetTeamsViewModel();
            var model = _matchesService.GetViewModelByID(id, teams);
            return View("AddMatch", model);
        }
        [HttpPost]
        public ActionResult AddMatchToDB(int homeTeamId, int awayTeamId, int homeTeamGoalsScored, int awayTeamGoalsScored)
        {
            ValidateData(homeTeamId, awayTeamId, homeTeamGoalsScored, awayTeamGoalsScored);
            if (ModelState.IsValid)
            {
                _matchesService.AddNewMatchToDB(homeTeamId, awayTeamId, homeTeamGoalsScored, awayTeamGoalsScored);
                _teamsService.ReCalculateTeamsPoints();
                return RedirectToAction("Index");
            }
            else
            {
                var teams = _teamsService.GetTeamsViewModel();
                var model = _matchesService.CreateNewModel(teams);
                return View("AddMatch", model);
            }
            
        }
        [HttpPost]
        public ActionResult UpdateMatch(int id, int homeTeamId, int awayTeamId, int homeTeamGoalsScored, int awayTeamGoalsScored)
        {
            ValidateData(homeTeamId, awayTeamId, homeTeamGoalsScored, awayTeamGoalsScored);
            if (ModelState.IsValid)
            {
                _matchesService.EditMatch(id, homeTeamId, awayTeamId, homeTeamGoalsScored, awayTeamGoalsScored);
                _teamsService.ReCalculateTeamsPoints();
                return RedirectToAction("Index");
            }
            else
            {
                var teams = _teamsService.GetTeamsViewModel();
                var model = _matchesService.CreateNewModel(teams, id, homeTeamId, awayTeamId, homeTeamGoalsScored, awayTeamGoalsScored);
                return View("AddMatch", model);
            }
        }
        private void ValidateData(int homeTeamId, int awayTeamId, int homeTeamGoals, int awayTeamGoals)
        {
            if (homeTeamId == awayTeamId)
            {
                ModelState.AddModelError("AwayTeamId", sameTeamError);
            }
            if (awayTeamGoals < 0)
            {
                ModelState.AddModelError("AwayTeamGoalsScored", negativeGoalsError);
            }
            if (homeTeamGoals < 0)
            {
                ModelState.AddModelError("HomeTeamGoalsScored", negativeGoalsError);
            }
        }
        //private List<TeamsComboBoxViewModel> GetTeams() 
        //{
        //    return _teamsService.GetTeamsViewModel();
        //}
        public ActionResult DeleteMatch(int id)
        {
            _matchesService.Delete(id);
            _teamsService.ReCalculateTeamsPoints();
            return RedirectToAction("Index");
        }
    }
}

FootballLeague/FootballLeague/Controllers/TeamsController.cs
using DAL;
using Models;
//using Repositories.UnitOfWork;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FootballLeague.Controllers
{
    public class TeamsController : Controller
    {
        // GET: Teams
        //private IUnitOfWork _unitOfWork;
        private ITeamsService _teamsService;
        public TeamsController( ITeamsService teamsService)
        {
            //_unitOfWork = unitOfWork;
            _teamsService = teamsService;
        }
        public ActionResult Index()
        {
            var model = _teamsService.GetAll();
            return View(model);
        }
        public ActionResult AddTeam()
        {
            var model = new Team();
            return View(model);
        }
        public ActionResult EditTeam(int id)
        {
            var model = _teamsService.GetByID(id);
            return View("AddTeam", model);
        }
        [HttpPost]
        public ActionResult AddTeamToDB(string name)
        {
            _teamsService.AddNewTeamToDB(name);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult UpdateTeam(int id,string name)
        {
            _teamsService.EditTeam(id, name);
            return RedirectToAction("Index");
        }
        
        public ActionResult DeleteTeam(int id)
        {
            _teamsService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

FootballLeague/FootballLeague/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FootballLeague/FootballLeague/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FootballLeague/FootballLeague/Views/Matches/AddMatch.cshtml
@model Models.MatchViewModel
@{
    var isNew = Model.Id == 0 ? true : false;
    var saveButtonText = isNew ? "Add" : "Save";
    var headerText = isNew ? "Add Match" : "Edit Match";
}
<h2>@headerText</h2>

@using (Html.BeginForm(isNew ? "AddMatchToDB" : "UpdateMatch", "Matches", FormMethod.Post))
{
    if (!isNew)
    {
        @Html.HiddenFor(model => model.Id)
    }
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @*@Html.HiddenFor(model => model.Name)*@
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Home Team</th>
                <th scope="col">Home Team Goals</th>
                <th scope="col">Away Team Goals</th>
                <th scope="col">Away Team</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DropDownListFor(m => m.HomeTeamId,
                        new SelectList(@Model.Teams, "Id", "Name"),
                        new { @class = "form-control" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.HomeTeamId, "", new { @class = "text-danger", style = "width:50px" })
                    @Html.EditorFor(model => model.HomeTeamGoalsScored, new { htmlAttributes = new { @class = "form-control", style = "width:50px" } })
                </td>
                <td>
                    @Html.EditorFor(model => model.AwayTeamGoalsScored, new { htmlAttributes = new { @class = "form-control", style = "width:50px" } })
                </td>
                <td>
                    @Html.DropDownListFor(m => m.AwayTeamId,
               new SelectList(@Model.Teams, "Id", "Name"),
               new { @class = "form-control" })
                </td>
            </tr>
        </tbody>
    </table>
    

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="@saveButtonText" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FootballLeague/FootballLeague/Views/Matches/Index.cshtml
@model List<DAL.Match>
    <div style="padding-top: 15px">
        <button type="button" class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("AddMatch", "Matches") + "'");">Add Match</button>
        @*<button type="button" class="btn btn-primary">Add Match</button>*@
    </div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Matches</th>
        </tr>
    </thead>
    <tbody>

        @for (int i = 0; i < Model.Count; i++)
        {
            var item = Model[i];
            var position = i + 1;
        <tr>
            <th scope="row">@position</th>
            <td>@item.HomeTeam.Name  @item.HomeTeamGoalsScored - @item.AwayTeamGoalsScored  @item.AwayTeam.Name</td>
            <td>@Html.ActionLink("Edit", "EditMatch", new { id = item.Id }) | @Html.ActionLink("Delete", "DeleteMatch", new { id = item.Id }) </td>
        </tr>
        }
    </tbody>
</table>

FootballLeague/FootballLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Teams", "Index", "Teams")</li>
                    <li>@Html.ActionLink("Matches", "Index", "Matches")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Football League</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>